services:
  postgres:
    image: postgres:14.10-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: workstation-rack
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"
    networks:
      - workstation-rack-net
    volumes:
      - ./db/init-db:/docker-entrypoint-initdb.d
    container_name: workstation-rack-db
    healthcheck:
      test: [ "CMD-SHELL", "psql -U postgres -d workstation-rack -t 15 -c 'SELECT 1'" ]
      interval: "5s"
      timeout: "15s"
      retries: 10

networks:
  workstation-rack-net:
    driver: bridge