

quarkus:


  datasource:
    db-kind: postgresql
    devservices:
      enabled: true
      reuse: false
      image-name: "postgres:14.10-alpine"
      container-env:
        "POSTGRES_DB": "workstation-rack"
        "POSTGRES_USER": "postgres"
        "PASSWORD": "postgres"
      port: 5433
      volumes:
        "db/init-db": "/docker-entrypoint-initdb.d"
      db-name: "workstation-rack"
      username: "postgres"
      password: "postgres"
    jdbc:
      url: jdbc:postgresql://localhost:5433/workstation-rack
      initial-size: 2
      min-size: 2
      max-size: 5

  liquibase:
    migrate-at-start: true
    search-path:
      - "db/changelog"
    change-log: "db/changelog.xml"

  hibernate-orm:
    packages: com.ctw.workstation
    validate-in-dev-mode: false
    database:
      generation: none
    log:
      sql: ${hibernate_orm_log_sql:false}
  rest-client:
    external-api:
      url: "http://bmw.external.com"

#Frontend e Backend em portas diferentes
  http:
    cors:
      enabled: true
      origins: "http://localhost:4200"
#  log:
#    level: INFO
#    min-level: INFO
#    category: "org.hibernate"